; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "SeaDAS"
#define MyAppVersion "12.0.0"
#define MyAppPublisher "NASA"
#define MyAppURL "https://seadas.gsfc.nasa.gov"
#define MyAppExeName "seadas.exe"
#define ArchiveDotSeaDASScriptName "archiveDotSeaDAS_windows.bat"
#define ShortcutIconFileName1 "seadas_installer_icon.ico"
#define ShortcutIconFileName2 "seadas_icon.ico"


[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)

[Setup]
;SignTool=signtool  /n $qNASA OEL$q /t http://timestamp.comodoca.com/authenticode  /d $qSeaDAS Installer$q $f
AppId={{A27DCD92-CD65-440A-93C7-F1A52967E2E4}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UsePreviousAppDir=no
DisableProgramGroupPage=yes
LicenseFile=C:\Users\aabduraz\MainDev\installers\Windows-Installer-Files\seadas_license.rtf
InfoBeforeFile=C:\Users\aabduraz\MainDev\installers\Windows-Installer-Files\seadas_installer_welcome_message.rtf
;InfoAfterFile=C:\Users\aynur\izpack\finish.html
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputDir=C:\Users\aabduraz\MainDev\installers\Windows-Installer-Files
OutputBaseFilename=seadas_12.0.0_windows64_installer
SetupIconFile=C:\Users\aabduraz\MainDev\installers\Windows-Installer-Files\seadas_installer_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
DisableWelcomePage=no
DisableDirPage=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[INI]
Filename: "{app}\etc\seadas.conf"; Section: "Default location of JRE"; Key: "jdkhome"; String: "{app}\jdk-21.0.8+9-jre"

[Files]
Source: "C:\Users\aabduraz\SeaDAS12\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source:  "C:\Users\aabduraz\MainDev\installers\Windows-Installer-Files\*.ico"; DestDir: "{app}";
; NOTE: Don't use "Flags: ignoreversion" on any shared system files



[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}";  HotKey: "ctrl+alt+s"; IconFilename: "{app}\{#ShortcutIconFileName1}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"; Tasks: desktopicon;  IconFilename: "{app}\{#ShortcutIconFileName2}"

[Run]
Filename: "{app}\bin\{#ArchiveDotSeaDASScriptName}"; Description: "Archive the .seadas8 directory."; Flags: nowait postinstall skipifsilent
Filename: "{app}\bin\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

